'use strict'

class ConvertUnicode {
  async convert (str) {
    // Replace accented characters
    str.replace('%U00C0', 'À')
    str.replace('%U00C1', 'Á')
    str.replace('%U00C2', 'Â')
    str.replace('%U00C3', 'Ã')
    str.replace('%U00C4', 'Ä')
    str.replace('%U00C5', 'Å')
    str.replace('%U00C6', 'Æ')
    str.replace('%U00C7', 'Ç')
    str.replace('%U00C8', 'È')
    str.replace('%U00C9', 'É')
    str.replace('%U00CA', 'Ê')
    str.replace('%U00CB', 'Ë')
    str.replace('%U00CC', 'Ì')
    str.replace('%U00CD', 'Í')
    str.replace('%U00CE', 'Î')
    str.replace('%U00CF', 'Ï')
    str.replace('%U00D1', 'Ñ')
    str.replace('%U00D2', 'Ò')
    str.replace('%U00D3', 'Ó')
    str.replace('%U00D4', 'Ô')
    str.replace('%U00D5', 'Õ')
    str.replace('%U00D6', 'Ö')
    str.replace('%U00D8', 'Ø')
    str.replace('%U00D9', 'Ù')
    str.replace('%U00DA', 'Ú')
    str.replace('%U00DB', 'Û')
    str.replace('%U00DC', 'Ü')
    str.replace('%U00DD', 'Ý')

    // Now lower case accents
    str.replace('%U00DF', 'ß')
    str.replace('%U00E0', 'à')
    str.replace('%U00E1', 'á')
    str.replace('%U00E2', 'â')
    str.replace('%U00E3', 'ã')
    str.replace('%U00E4', 'ä')
    str.replace('%U00E5', 'å')
    str.replace('%U00E6', 'æ')
    str.replace('%U00E7', 'ç')
    str.replace('%U00E8', 'è')
    str.replace('%U00E9', 'é')
    str.replace('%U00EA', 'ê')
    str.replace('%U00EB', 'ë')
    str.replace('%U00EC', 'ì')
    str.replace('%U00ED', 'í')
    str.replace('%U00EE', 'î')
    str.replace('%U00EF', 'ï')
    str.replace('%U00F0', 'ð')
    str.replace('%U00F1', 'ñ')
    str.replace('%U00F2', 'ò')
    str.replace('%U00F3', 'ó')
    str.replace('%U00F4', 'ô')
    str.replace('%U00F5', 'õ')
    str.replace('%U00F6', 'ö')
    str.replace('%U00F8', 'ø')
    str.replace('%U00F9', 'ù')
    str.replace('%U00FA', 'ú')
    str.replace('%U00FB', 'û')
    str.replace('%U00FC', 'ü')
    str.replace('%U00FD', 'ý')
    str.replace('%U00FF', 'ÿ')

    return str
  }
}

module.exports = ConvertUnicode
