'use strict'

class ConvertUnicode {
  async convert (str) {
    return str.replace(/%U00C0/g, 'À')
      .replace(/%U00C1/g, 'Á')
      .replace(/%U00C2/g, 'Â')
      .replace(/%U00C3/g, 'Ã')
      .replace(/%U00C4/g, 'Ä')
      .replace(/%U00C5/g, 'Å')
      .replace(/%U00C6/g, 'Æ')
      .replace(/%U00C7/g, 'Ç')
      .replace(/%U00C8/g, 'È')
      .replace(/%U00C9/g, 'É')
      .replace(/%U00CA/g, 'Ê')
      .replace(/%U00CB/g, 'Ë')
      .replace(/%U00CC/g, 'Ì')
      .replace(/%U00CD/g, 'Í')
      .replace(/%U00CE/g, 'Î')
      .replace(/%U00CF/g, 'Ï')
      .replace(/%U00D1/g, 'Ñ')
      .replace(/%U00D2/g, 'Ò')
      .replace(/%U00D3/g, 'Ó')
      .replace(/%U00D4/g, 'Ô')
      .replace(/%U00D5/g, 'Õ')
      .replace(/%U00D6/g, 'Ö')
      .replace(/%U00D8/g, 'Ø')
      .replace(/%U00D9/g, 'Ù')
      .replace(/%U00DA/g, 'Ú')
      .replace(/%U00DB/g, 'Û')
      .replace(/%U00DC/g, 'Ü')
      .replace(/%U00DD/g, 'Ý')
      .replace(/%U00DF/g, 'ß')
      .replace(/%U00E0/g, 'à')
      .replace(/%U00E1/g, 'á')
      .replace(/%U00E2/g, 'â')
      .replace(/%U00E3/g, 'ã')
      .replace(/%U00E4/g, 'ä')
      .replace(/%U00E5/g, 'å')
      .replace(/%U00E6/g, 'æ')
      .replace(/%U00E7/g, 'ç')
      .replace(/%U00E8/g, 'è')
      .replace(/%U00E9/g, 'é')
      .replace(/%U00EA/g, 'ê')
      .replace(/%U00EB/g, 'ë')
      .replace(/%U00EC/g, 'ì')
      .replace(/%U00ED/g, 'í')
      .replace(/%U00EE/g, 'î')
      .replace(/%U00EF/g, 'ï')
      .replace(/%U00F0/g, 'ð')
      .replace(/%U00F1/g, 'ñ')
      .replace(/%U00F2/g, 'ò')
      .replace(/%U00F3/g, 'ó')
      .replace(/%U00F4/g, 'ô')
      .replace(/%U00F5/g, 'õ')
      .replace(/%U00F6/g, 'ö')
      .replace(/%U00F8/g, 'ø')
      .replace(/%U00F9/g, 'ù')
      .replace(/%U00FA/g, 'ú')
      .replace(/%U00FB/g, 'û')
      .replace(/%U00FC/g, 'ü')
      .replace(/%U00FD/g, 'ý')
      .replace(/%U00FF/g, 'ÿ')
  }
}

module.exports = ConvertUnicode
